"""HTML business report generator.

Produces a self-contained HTML file with KPIs, segment summary, churn
distribution, NBA preview, etc. Uses Jinja2 and inline CSS so the report
can be opened directly in a browser without any server.
"""
from __future__ import annotations
from datetime import datetime
from pathlib import Path
import pandas as pd

from jinja2 import Template

from src.config import PROJECT_ROOT


_REPORT_CSS = (
    "body{font-family:-apple-system,\"PingFang SC\",\"Microsoft YaHei\",sans-serif;"
    "max-width:1100px;margin:32px auto;padding:0 24px;color:#222}"
    "h1{font-size:28px;margin-bottom:4px}"
    "h2{border-left:4px solid #3a6df0;padding-left:8px;margin-top:32px}"
    ".meta{color:#666;font-size:13px;margin-bottom:24px}"
    ".kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:16px 0}"
    ".kpi{background:#f6f8fa;border-radius:8px;padding:16px}"
    ".kpi .label{font-size:12px;color:#666}"
    ".kpi .value{font-size:22px;font-weight:600;color:#3a6df0}"
    "table{border-collapse:collapse;width:100%;font-size:13px;margin-top:12px}"
    "th,td{border:1px solid #e1e4e8;padding:6px 10px;text-align:left}"
    "th{background:#f6f8fa}"
    ".P0{color:#d73a49;font-weight:600}"
    ".P1{color:#e36209}"
    ".P2{color:#6f42c1}"
    ".P3{color:#586069}"
    ".footer{margin-top:40px;font-size:12px;color:#888;text-align:center}"
)

_REPORT_BODY = """<h1>电商 RFM 业务分析报告</h1>
<div class="meta">生成时间: {{ generated_at }} · 数据源: {{ dataset_name }} · 客户数: {{ n_customers }} · 交易数: {{ n_transactions }}</div>

<h2>核心指标</h2>
<div class="kpi-grid">
  {% for k, v in kpis.items() %}<div class="kpi"><div class="label">{{ k }}</div><div class="value">{{ v }}</div></div>{% endfor %}
</div>

<h2>客户分群</h2>
<table>
  <thead><tr><th>Cluster</th><th>业务标签</th><th>优先级</th><th>客户数</th><th>营收占比</th><th>一句话定位</th></tr></thead>
  <tbody>
    {% for seg in segments %}
    <tr>
      <td>{{ seg.cluster_id }}</td>
      <td>{{ seg.business_name }}</td>
      <td class="{{ seg.priority }}">{{ seg.priority }}</td>
      <td>{{ seg.customers }}</td>
      <td>{{ seg.revenue_share_pct }}%</td>
      <td>{{ seg.tagline }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<h2>CLV 概览</h2>
<table>
  <thead><tr><th>指标</th><th>数值</th></tr></thead>
  <tbody>
    {% for k, v in clv_summary.items() %}<tr><td>{{ k }}</td><td>{{ v }}</td></tr>{% endfor %}
  </tbody>
</table>

<h2>流失风险分布</h2>
<table>
  <thead><tr><th>风险分桶</th><th>客户数</th><th>占比</th></tr></thead>
  <tbody>
    {% for row in churn_buckets %}<tr><td>{{ row.label }}</td><td>{{ row.n }}</td><td>{{ row.pct }}%</td></tr>{% endfor %}
  </tbody>
</table>

<h2>Top 10 Next-Best-Action</h2>
<table>
  <thead><tr><th>Customer</th><th>Segment</th><th>推荐动作</th><th>渠道</th><th>预期转化</th><th>预期 ROI</th><th>理由</th></tr></thead>
  <tbody>
    {% for row in nba_top %}
    <tr>
      <td>{{ row.customer_id }}</td>
      <td>{{ row.segment_name }}</td>
      <td>{{ row.recommended_action }}</td>
      <td>{{ row.channel }}</td>
      <td>{{ row.expected_conversion_rate }}</td>
      <td>{{ row.expected_roi }}</td>
      <td>{{ row.reasoning }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<h2>Chat-with-Data 演示示例</h2>
<table>
  <thead><tr><th>问题</th><th>回答</th></tr></thead>
  <tbody>
    {% for qa in chat_examples %}<tr><td>{{ qa.question }}</td><td>{{ qa.answer }}</td></tr>{% endfor %}
  </tbody>
</table>

<div class="footer">Generated by ecommerce-rfm-customer-segmentation</div>
"""

REPORT_TEMPLATE = (
    "<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\">"
    "<title>电商 RFM 业务分析报告</title>"
    "<style>" + _REPORT_CSS + "</style></head><body>"
    + _REPORT_BODY + "</body></html>"
)


def _kpis(rfm, n_transactions):
    revenue = float(rfm["Monetary"].sum()) if "Monetary" in rfm.columns else 0
    avg_basket = float(rfm.get("avg_basket", pd.Series([0])).mean())
    freq = float(rfm["Frequency"].mean()) if "Frequency" in rfm.columns else 0
    return {
        "客户数": f"{len(rfm):,}",
        "营收总额": f"${revenue:,.0f}",
        "平均购买次数": f"{freq:.1f}",
        "平均客单": f"${avg_basket:.2f}",
    }


def _churn_buckets(rfm):
    if "churn_prob" not in rfm.columns:
        return []
    bins = [0.0, 0.3, 0.6, 0.8, 1.01]
    labels = ["低风险 (<0.3)", "中风险 (0.3-0.6)", "高风险 (0.6-0.8)", "极高风险 (>0.8)"]
    s = pd.cut(rfm["churn_prob"], bins=bins, labels=labels, include_lowest=True)
    counts = s.value_counts().reindex(labels, fill_value=0)
    total = counts.sum() or 1
    return [
        {"label": str(name), "n": int(c), "pct": round(c / total * 100, 1)}
        for name, c in counts.items()
    ]


def build_html_report(
    rfm, segments_payload, clv_payload, nba_payload,
    chat_examples=None, dataset_name="unknown", n_transactions=0,
    out_path=None,
):
    chat_examples = chat_examples or []
    segments = segments_payload.get("segments", [])
    profile_map = {int(p["Cluster"]): p for p in segments_payload.get("profile", [])}
    for s in segments:
        cid = int(s.get("cluster_id", -1))
        if cid in profile_map:
            s["customers"] = profile_map[cid].get("customers", s.get("customers", ""))
            s["revenue_share_pct"] = profile_map[cid].get(
                "revenue_share_pct", s.get("revenue_share_pct", "")
            )
    kpis = _kpis(rfm, n_transactions)
    clv_summary = clv_payload or {}
    churn_buckets = _churn_buckets(rfm)
    nba_rows = nba_payload.get("nba", [])
    seg_name_by_id = {int(s["cluster_id"]): s.get("business_name", "") for s in segments}
    nba_top_df = pd.DataFrame(nba_rows[:10])
    if not nba_top_df.empty and "Cluster" in rfm.columns:
        cid_to_cluster = {str(k): v for k, v in rfm["Cluster"].to_dict().items()}
        nba_top_df["segment_name"] = nba_top_df["customer_id"].map(
            lambda x: seg_name_by_id.get(int(cid_to_cluster.get(str(x), -1)), "")
        )
    nba_top = nba_top_df.to_dict(orient="records") if not nba_top_df.empty else []
    template = Template(REPORT_TEMPLATE)
    html = template.render(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        dataset_name=dataset_name,
        n_customers=len(rfm),
        n_transactions=n_transactions,
        kpis=kpis,
        segments=segments,
        clv_summary=clv_summary,
        churn_buckets=churn_buckets,
        nba_top=nba_top,
        chat_examples=chat_examples,
    )
    if out_path is None:
        out_path = PROJECT_ROOT / "reports" / "business_report.html"
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    return str(out_path)
